"""Tonnetz (tone network) computation for harmonic visualization"""

import numpy as np
from typing import Dict, List, Any, Tuple
import logging

logger = logging.getLogger(__name__)

# Pitch class names
PITCH_CLASSES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']

# Tonnetz is generated by two intervals:
# - Perfect fifth (7 semitones)
# - Major third (4 semitones)
# This creates a 2D lattice that wraps into a torus


def pitch_class_to_tonnetz_2d(pc: int) -> Tuple[float, float]:
    """
    Map pitch class (0-11) to 2D Tonnetz grid coordinates.

    The Tonnetz is arranged so that:
    - Moving right = +7 semitones (perfect fifth)
    - Moving up-right = +4 semitones (major third)
    - Moving up-left = +3 semitones (minor third)

    Returns (x, y) coordinates on hexagonal grid.
    """
    # Position along circle of fifths (x-axis)
    fifths_position = (pc * 7) % 12

    # Position along thirds axis (y-axis)
    # We use the relationship: going up a major third = (pc + 4) mod 12
    # Going around 3 major thirds returns to start: 4 * 3 = 12
    thirds_position = (pc * 4) % 12

    # Normalize to unit coordinates
    x = fifths_position / 12.0
    y = thirds_position / 12.0

    return (x, y)


def pitch_class_to_torus(pc: int, major_radius: float = 2.0, minor_radius: float = 0.8) -> Dict[str, float]:
    """
    Map pitch class (0-11) to 3D torus coordinates.

    The torus has:
    - Major circle (around the donut) = circle of fifths
    - Minor circle (tube cross-section) = circle of thirds

    Args:
        pc: Pitch class (0-11)
        major_radius: Radius of the main torus circle
        minor_radius: Radius of the tube

    Returns:
        Dict with x, y, z coordinates and angles
    """
    # Theta: angle around the major circle (circle of fifths)
    # Each pitch class is 7 semitones apart in fifths order
    fifths_order = (pc * 7) % 12
    theta = (fifths_order / 12.0) * 2 * np.pi

    # Phi: angle around the minor circle (thirds)
    # Major thirds divide the octave into 3 parts
    thirds_order = (pc * 4) % 12
    phi = (thirds_order / 12.0) * 2 * np.pi

    # Torus parametric equations
    x = (major_radius + minor_radius * np.cos(phi)) * np.cos(theta)
    y = (major_radius + minor_radius * np.cos(phi)) * np.sin(theta)
    z = minor_radius * np.sin(phi)

    return {
        "x": float(x),
        "y": float(y),
        "z": float(z),
        "theta": float(theta),
        "phi": float(phi),
        "pitch_class": pc,
        "pitch_class_name": PITCH_CLASSES[pc]
    }


def compute_tonnetz_trajectory(
    time_series: List[Dict],
    major_radius: float = 2.0,
    minor_radius: float = 0.8
) -> Dict[str, Any]:
    """
    Compute Tonnetz trajectory for animation.

    Args:
        time_series: List of notes with time, pitch_class info
        major_radius: Torus major radius
        minor_radius: Torus minor radius

    Returns:
        Tonnetz visualization data including trajectory and static positions
    """
    # Static positions for all 12 pitch classes
    static_positions = []
    for pc in range(12):
        pos = pitch_class_to_torus(pc, major_radius, minor_radius)
        static_positions.append(pos)

    # Trajectory: note events over time with torus positions
    trajectory = []
    for note in sorted(time_series, key=lambda n: n["time"]):
        pc = note["pitch_class"] if "pitch_class" in note else note["pitch"] % 12
        pos = pitch_class_to_torus(pc, major_radius, minor_radius)

        trajectory.append({
            "time": note["time"],
            "duration": note["duration"],
            "pitch": note["pitch"],
            "pitch_class": pc,
            "pitch_class_name": PITCH_CLASSES[pc],
            "velocity": note["velocity"],
            "x": pos["x"],
            "y": pos["y"],
            "z": pos["z"],
            "theta": pos["theta"],
            "phi": pos["phi"]
        })

    # Compute chord events (simultaneous notes)
    chord_events = _detect_chord_events(time_series, major_radius, minor_radius)

    # Pitch class activity over time (for heatmap)
    activity = _compute_pitch_class_activity(time_series)

    return {
        "static_positions": static_positions,
        "trajectory": trajectory,
        "chord_events": chord_events,
        "pitch_class_activity": activity,
        "torus_params": {
            "major_radius": major_radius,
            "minor_radius": minor_radius
        }
    }


def _detect_chord_events(
    time_series: List[Dict],
    major_radius: float,
    minor_radius: float,
    tolerance: float = 0.05
) -> List[Dict]:
    """
    Detect chord events (simultaneous notes) and classify them.

    Args:
        time_series: List of notes
        major_radius: Torus major radius
        minor_radius: Torus minor radius
        tolerance: Time tolerance for considering notes simultaneous

    Returns:
        List of chord events with positions and classifications
    """
    if not time_series:
        return []

    # Group notes by time (within tolerance)
    sorted_notes = sorted(time_series, key=lambda n: n["time"])
    chord_events = []

    i = 0
    while i < len(sorted_notes):
        # Collect all notes starting at approximately the same time
        chord_notes = [sorted_notes[i]]
        j = i + 1
        while j < len(sorted_notes) and sorted_notes[j]["time"] - sorted_notes[i]["time"] < tolerance:
            chord_notes.append(sorted_notes[j])
            j += 1

        if len(chord_notes) >= 2:
            # Get unique pitch classes
            pcs = list(set(
                n["pitch_class"] if "pitch_class" in n else n["pitch"] % 12
                for n in chord_notes
            ))

            # Get center of mass position on torus
            positions = [pitch_class_to_torus(pc, major_radius, minor_radius) for pc in pcs]
            center_x = np.mean([p["x"] for p in positions])
            center_y = np.mean([p["y"] for p in positions])
            center_z = np.mean([p["z"] for p in positions])

            # Classify chord type
            chord_type, root = _classify_chord(pcs)

            # Get duration (minimum of all notes)
            duration = min(n["duration"] for n in chord_notes)

            chord_events.append({
                "time": chord_notes[0]["time"],
                "duration": duration,
                "pitch_classes": sorted(pcs),
                "pitch_class_names": [PITCH_CLASSES[pc] for pc in sorted(pcs)],
                "chord_type": chord_type,
                "root": PITCH_CLASSES[root] if root is not None else None,
                "center_x": float(center_x),
                "center_y": float(center_y),
                "center_z": float(center_z),
                "positions": positions
            })

        i = j

    return chord_events


def _classify_chord(pitch_classes: List[int]) -> Tuple[str, int]:
    """
    Classify a chord based on its pitch classes.

    Returns:
        Tuple of (chord_type, root_pitch_class)
    """
    if len(pitch_classes) < 2:
        return ("single", pitch_classes[0] if pitch_classes else None)

    pcs = set(pitch_classes)

    # Check for common chord types by interval structure
    for root in range(12):
        # Major triad: root, M3, P5 (0, 4, 7)
        if {root, (root + 4) % 12, (root + 7) % 12} == pcs:
            return ("major", root)

        # Minor triad: root, m3, P5 (0, 3, 7)
        if {root, (root + 3) % 12, (root + 7) % 12} == pcs:
            return ("minor", root)

        # Diminished triad: root, m3, d5 (0, 3, 6)
        if {root, (root + 3) % 12, (root + 6) % 12} == pcs:
            return ("diminished", root)

        # Augmented triad: root, M3, A5 (0, 4, 8)
        if {root, (root + 4) % 12, (root + 8) % 12} == pcs:
            return ("augmented", root)

        # Dominant 7th: root, M3, P5, m7 (0, 4, 7, 10)
        if {root, (root + 4) % 12, (root + 7) % 12, (root + 10) % 12} == pcs:
            return ("dominant7", root)

        # Major 7th: root, M3, P5, M7 (0, 4, 7, 11)
        if {root, (root + 4) % 12, (root + 7) % 12, (root + 11) % 12} == pcs:
            return ("major7", root)

        # Minor 7th: root, m3, P5, m7 (0, 3, 7, 10)
        if {root, (root + 3) % 12, (root + 7) % 12, (root + 10) % 12} == pcs:
            return ("minor7", root)

    # Power chord / fifth
    for root in range(12):
        if {root, (root + 7) % 12} == pcs:
            return ("power", root)

    # Couldn't classify
    return ("other", min(pitch_classes))


def _compute_pitch_class_activity(time_series: List[Dict]) -> List[Dict]:
    """
    Compute pitch class activity histogram over time windows.
    """
    if not time_series:
        return []

    # Get time range
    min_time = min(n["time"] for n in time_series)
    max_time = max(n["time"] + n["duration"] for n in time_series)

    # Create time windows (1 second each)
    window_size = 1.0
    activity = []

    current_time = min_time
    while current_time < max_time:
        window_end = current_time + window_size

        # Count active pitch classes in this window
        pc_counts = [0] * 12
        for note in time_series:
            note_start = note["time"]
            note_end = note["time"] + note["duration"]

            # Check if note overlaps with window
            if note_start < window_end and note_end > current_time:
                pc = note["pitch_class"] if "pitch_class" in note else note["pitch"] % 12
                # Weight by velocity
                pc_counts[pc] += note["velocity"] / 127.0

        # Normalize
        total = sum(pc_counts)
        if total > 0:
            pc_counts = [c / total for c in pc_counts]

        activity.append({
            "time": current_time + window_size / 2,
            "distribution": pc_counts
        })

        current_time += window_size

    return activity


def compute_2d_tonnetz_coordinates() -> List[Dict]:
    """
    Compute 2D Tonnetz grid coordinates for visualization.

    Returns a list of pitch class positions in a hexagonal grid layout.
    """
    coordinates = []

    # Hexagonal grid layout
    # The Tonnetz is arranged with:
    # - Horizontal: perfect fifths (C-G-D-A-E-B-F#-C#-G#-D#-A#-F-C)
    # - Diagonal up-right: major thirds
    # - Diagonal up-left: minor thirds

    for pc in range(12):
        # Position in circle of fifths
        fifths_pos = (pc * 7) % 12

        # Row based on how many "thirds" steps from C
        row = (pc * 4) % 3  # Groups into 3 rows

        # Hexagonal offset
        x = fifths_pos + (row * 0.5)
        y = row * 0.866  # sqrt(3)/2 for hexagonal spacing

        coordinates.append({
            "pitch_class": pc,
            "pitch_class_name": PITCH_CLASSES[pc],
            "x": float(x),
            "y": float(y),
            "fifths_position": fifths_pos
        })

    return coordinates
